### ISSUE TITLE
Remove the OTel spec vesion

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-telemetry#100]
We need to remove the OTel spec version from the spec doc as OpenTelemetry-java does not fully implement any particular version of the OTel spec. At the moment, the spec says 1.13 but it was incorrect.

**Comment by JanWesterkamp-iJUG** [comment]
But there is a hard coded link to the OTel spec version and Semantic Conventions here we need to take into account:

https://github.com/open-telemetry/opentelemetry-java/blob/749d3164cce52a81a5d52882c4a5f716cfd2f3a3/buildscripts/semantic-convention/generate.sh#L7C1-L8C31

I think we need to link them but take into account which features included/excluded regarding the four sepcs (Tracing, Metrics Loggging and Baggage).

**Comment by pdudits** [comment]
If at the same time we want to allow vendors to upgrade their opentelemetry tooling and thus use more recent `opentelemetry-java` I think we can express the requirement as well as enough explanation like this:

As an explanation for users the Introduction or Architecture section of spec should state that the spec aims to support AT MINIMUM the feature set of {otel-java-version}, which implements most of {otel-spec-version} as described in compliance matrix.

The API requirement should state, that vendor must provide OpenTelemetry API and Autoconfigure SPI in versions that are _binary compatible_ to {otel-java-version}; thus allowing for more recent version provided there are no incompatible API changes, which they claim to guarantee.

And finally, an implementation must fullfill the _requirements_ of Semantic conventions `1.20.0` for span names and HTTP inbound and outbound communications.

I believe requirement for stable semantic conventions will require new major release of the spec, and until then `opentelemetry-java` will not change their support for 1.x semantic conventions.

**Comment by Emily-Jiang** [comment]
> But there is a hard coded link to the OTel spec version and Semantic Conventions here we need to take into account:
> 
> https://github.com/open-telemetry/opentelemetry-java/blob/749d3164cce52a81a5d52882c4a5f716cfd2f3a3/buildscripts/semantic-convention/generate.sh#L7C1-L8C31
> 
I joined today's OTel Java call. The version was only used to defined the constants required in the OTel spec. The implementation matrix is [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md).

> I think we need to link them but take into account which features included/excluded regarding the four sepcs (Tracing, Metrics Loggging and Baggage).
> 
> May be we can solve this to reference to the compatibility matrix in our spec:
> 
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md
