### ISSUE TITLE
Rewrite JaxRsServerAsyncTest to not depend directly on Jakarta EE Concurrency

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-telemetry#140]
JaxRsServerAsyncTest currently depends on Jakarta EE Concurrency by [injection of a `ManagedExecutorService` resource][ee-injection].

However, the only requirement for this test is that the `CompletionStage` is not completed until after the `getCompletionStage` resource method returns. While the concurrency spec is the way to do this in Jakarta EE, not all MP runtimes support that and there are other options.

We should rewrite this test so that it uses an `Executor` provided by the implementer running the TCK. That way the implementer can run the test with whatever async implementation is most appropriate in their runtime.

We should then make this test mandatory since it will no longer depend on Jakarta EE Concurrency.

[ee-injection]: https://github.com/eclipse/microprofile-telemetry/blob/9bd06a0d947ad04f66b116ed80674a7af9c84cb1/tracing/tck/src/main/java/org/eclipse/microprofile/telemetry/tracing/tck/async/JaxRsServerAsyncTestEndpoint.java#L75-L76

**Comment by Emily-Jiang** [comment]
dup of #143
