### ISSUE TITLE
Metrics TCK: Test Otlp exporter

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-telemetry#142]
**Description**

As a:

- [ ] Application user
- [x] Specification implementer

...I need to be able to:
ensure metrics added can be verified via the OTLP exporter

**Comment by yasmin-aumeeruddy** [comment]
This wouldn't be feasible for the TCK as testing the OTLP would require a test container. The implementations should be responsible for testing this if they support the otlp exporter.
