### ISSUE TITLE
Upgrade base OpenTelemetry API (and semantic conventions)

### ISSUE THREAD

**Issue by pdudits** [eclipse/microprofile-telemetry#150]
MP Telemetry 1.1 is based on OpenTelemetry 1.29.0,  at the time of writing latest release is v1.33.0.

Starting with v1.31.0 semantic convention APIs got separated from main repo, and technically completely removed from distribution -- it is no longer not part of `opentelemetry-bom-alpha`, and has different groupId: current version is `io.opentelemetry.semconv:opentelemetry-semconv:1.23.1-alpha`. The version also follows the version of the spec. It is therefore different (and newer than) `io.opentelemetry:opentelemetry-semconv:1.30.1-alpha`.

Therefore specification needs to explicitly name the version of semantic conventions the implementors should follow (1.29.0 follows semconv 1.20.0, at time of writing current version is 1.23.1). 

OpenTelemetry SDK itself does not directly depend on semconv, the few attributes are named directly in its codebase.

Therefore we need to decide whether we keep requiring semconv package to be accessible, if so, which exact version should it be.

Related to upgrading semantic conventions to newer version than 1.20 is the requirement of semantic version stability for which I will file another issue.

**Comment by Emily-Jiang** [comment]
We will base on the latest semantic convention apis.

**Comment by brunobat** [comment]
Please beware that on OpenTelemetry 1.32.0 was the last version supporting the legacy HTTP semantic conventions. We need to decide if we want to support only the new ones for 2.0.

**Comment by pdudits** [comment]
Per #153, we decided to only support the new ones for 2.0

**Comment by Emily-Jiang** [comment]
I think this issue has been addressed. Please reopen if you think otherwise.
