### ISSUE TITLE
Telemetry configuration review

### ISSUE THREAD

**Issue by brunobat** [eclipse/microprofile-telemetry#155]
Because of these issues on the OpenTelemetry side, the final form of how OPenTelemetry file configurations and merge semantics are being discusses here:
https://github.com/open-telemetry/opentelemetry-specification/pull/3850
https://github.com/open-telemetry/opentelemetry-specification/issues/3752

Once it is settled how to programatically configure the OTel Java SDK after the file configuration is added we need to revisit what was merged as part of https://github.com/eclipse/microprofile-telemetry/pull/148.

**Comment by Emily-Jiang** [comment]
It seems that [file based config ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/file-configuration.md)is experiment. Let's leave it for now. I suggest to move to the `Next` Milestone.

**Comment by brunobat** [comment]
We should not use the file configuration proposed by OpenTelemetry. 
All MP Telemetry implementations already have their own configuration sub-systems. There is little value on supporting this.
