### ISSUE TITLE
Check severity of logs in TCK

### ISSUE THREAD

**Issue by yasmin-aumeeruddy** [eclipse/microprofile-telemetry#174]
The logs TCK needs updating to check the Log Record data including the SeverityText and SeverityNumber: 

https://opentelemetry.io/docs/concepts/signals/logs/#log-record

**Comment by Emily-Jiang** [comment]
@yasmin-aumeeruddy have you done this?

**Comment by yasmin-aumeeruddy** [comment]
PR is here: https://github.com/eclipse/microprofile-telemetry/pull/186
