### ISSUE TITLE
Implement tests in a way that is not timestamp dependent

### ISSUE THREAD

**Issue by brunobat** [eclipse/microprofile-telemetry#44]
This line assumes spans will arrive in order:
https://github.com/eclipse/microprofile-telemetry/blob/bac62306cca48c46d8f19022efe3e656f59a3846/tracing/tck/src/main/java/org/eclipse/microprofile/telemetry/tracing/tck/exporter/InMemorySpanExporter.java#L52
That is not true in all cases.
A new method to get spans is needed where you pass some filters like the parent span id, span type, target... 
This will allow sturdy assertions.

**Comment by Emily-Jiang** [comment]
@brunobat do you have the details for this issue? If you do, please post it here. Otherwise, please close it.

**Comment by Emily-Jiang** [comment]
@Azquelt @yasmin-aumeeruddy will take a look at this.

**Comment by Emily-Jiang** [comment]
This issue might be fixed by #95
