### ISSUE TITLE
Create test setup with test containers

### ISSUE THREAD

**Issue by brunobat** [eclipse/microprofile-telemetry#5]
**Description**
Create test setup with test containers and a TCK module
As a:

- [ ] Application user
- [X] Specification implementer

...I need to be able to:

Provide the base setup to test the compatibility of the different containers. 

...which enables me to:

Prove that containers can produce OTel traces to open-source reference applications

**Comment by Emily-Jiang** [comment]
We discussed today and decided not to proceed with this.
