### ISSUE TITLE
Update OpenTelemetry Java Implementation Version

### ISSUE THREAD

**Issue by JanWesterkamp-iJUG** [eclipse/microprofile-telemetry#54]
The current version is 1.18.0 and 1.19.0 is expected to come soon.

Some of the existing links in the spec document are broken (version 1.14.0) - this need to be addressed.

A separate issue for the OpenTelemetry Spec version will be opened too.

**Comment by JanWesterkamp-iJUG** [comment]
@brunobat, I thougt you did that already? But now I found version 1.14.0 with the broken links is still the current version. I think we should at least bump it to 1.18.0 for now and fix the links. What do you think about it?

**Comment by JanWesterkamp-iJUG** [comment]
> please refresh your branch

Cool, I did an update to the current spec version too and fixed some broken links in the spec document with it. Can you please review?

So we are on the latest available Otel versions now - more to come soon.

**Comment by JanWesterkamp-iJUG** [comment]
@Emily-Jiang we might be able to close https://github.com/eclipse/microprofile-telemetry/issues/28 now, because we reached 1.18.0 now.

Hopefully the new Java instrumentation release will come soon to to be able to close this one too.

**Comment by JanWesterkamp-iJUG** [comment]
[Version 1.19.0 of the Otel Java is out](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.19.0) already, so now only waiting for the Otel Java Implementation 1.19.0 only...

**Comment by Emily-Jiang** [comment]
I guess this is solved. Closing now. Please reopen it if you think otherwise.
