### ISSUE TITLE
Update OpenTelemetry Spec Version

### ISSUE THREAD

**Issue by JanWesterkamp-iJUG** [eclipse/microprofile-telemetry#55]
The current version is 1.11.0 and 1.14.0 is expected to come soon.

Some of the existing links in the spec document are broken (version 1.11.0) or pointing to unversioned documents - this need to be addressed.

A separate issue for the OpenTelemetry Java Implementation version is opened too:
https://github.com/eclipse/microprofile-telemetry/issues/54

**Comment by JanWesterkamp-iJUG** [comment]
@Emily-Jiang, thanks for the approval and merge - so now wating for 1.14.0 to come to be abelto close this issue completely.

**Comment by JanWesterkamp-iJUG** [comment]
Here is the [PR](https://github.com/eclipse/microprofile-telemetry/pull/60) for the 1.14.0 spec version.

@brunobat and @Emily-Jiang, can you review, please?

**Comment by Emily-Jiang** [comment]
done
