### ISSUE TITLE
Updating Test and API dependencies

### ISSUE THREAD

**Issue by JanWesterkamp-iJUG** [eclipse/microprofile-telemetry#58]
We have some outdated/deviating dependencies, that should be fixed:

- JUnit 5 to 5.9.1 (not addressed in parent yet)
- Arquillian to 1.7.0.Alpha12 (optional, current version from parent 1.7.0.Alpha10)
- MP TCK BOM 3.0 to TBD (to update i.e. Arquillian, [MP Parent PR](https://github.com/eclipse/microprofile-parent/pull/67) available)
- MicroProfile Config to 3.0.2 (manually configured - should be taken from a now deprecated MP BOM)
- MicroProfile Rest Client 3.0.1 (manually configured - should be taken from a now deprecated MP BOM)

As the microprofile-bom is deprecated, I think we need different (or retried?) approach to manage MP internal dependencies. Just manually updating to the current versions might fix it for MP Telemetry for now.

These are on the latest version already:

- <version.rest-assured>5.2.0</version.rest-assured>
- <version.awaitility>4.2.0</version.awaitility>

Some of these are findings by the dependabot too:

- JUnit 5: https://github.com/eclipse/microprofile-telemetry/pull/47
- MP Config: https://github.com/eclipse/microprofile-telemetry/pull/50
- MP Rest Client: https://github.com/eclipse/microprofile-telemetry/pull/57
- MP Parent: https://github.com/eclipse/microprofile-telemetry/pull/51 (should be closed, because update adressed already)

So merging the 3 dependabot PRs (and closing the MP Parent one) should fix most of these issues and/or I can create an PR for the remaining/all.

@Emily-Jiang, what do you think?

**Comment by Emily-Jiang** [comment]
> We have some outdated/deviating dependencies, that should be fixed:
> 
>     * JUnit 5 to 5.9.1 (not addressed in parent yet)
> 
>     * Arquillian to 1.7.0.Alpha12 (optional, current version from parent 1.7.0.Alpha10)

I have asked Yasmin to try this out.
> 
>     * MP TCK BOM 3.0 to TBD (to update i.e. Arquillian, [MP Parent PR](https://github.com/eclipse/microprofile-parent/pull/67) available)
> 
>     * MicroProfile Config to 3.0.2 (manually configured - should be taken from a now deprecated MP BOM)
> 
>     * MicroProfile Rest Client 3.0.1 (manually configured - should be taken from a now deprecated MP BOM)
> 
Since these specs are only doing service release, I suggest you raise an issue there so that they can address that in the next release.
> 
> As the microprofile-bom is deprecated, I think we need different (or retried?) approach to manage MP internal dependencies. Just manually updating to the current versions might fix it for MP Telemetry for now.
> 
> These are on the latest version already:
> 
>     * <version.rest-assured>5.2.0</version.rest-assured>
> 
>     * <version.awaitility>4.2.0</version.awaitility>
> 
> 
> Some of these are findings by the dependabot too:
> 
>     * JUnit 5: [Bump junit-jupiter from 5.9.0 to 5.9.1 #47](https://github.com/eclipse/microprofile-telemetry/pull/47)
> 
>     * MP Config: [Bump microprofile-config-api from 3.0 to 3.0.2 #50](https://github.com/eclipse/microprofile-telemetry/pull/50)
> 
>     * MP Rest Client: [Bump microprofile-rest-client-api from 3.0 to 3.0.1 #57](https://github.com/eclipse/microprofile-telemetry/pull/57)
> 
>     * MP Parent: [Bump microprofile-parent from 2.5 to 3.0 #51](https://github.com/eclipse/microprofile-telemetry/pull/51) (should be closed, because update adressed already)
> 
> 
> So merging the 3 dependabot PRs (and closing the MP Parent one) should fix most of these issues and/or I can create an PR for the remaining/all.
> 
Normally, we don't pull in the service release changes as the apis are identical (service releases are not allowed to update apis). Anyway, I have merged the dependbot PRs.
> @Emily-Jiang, what do you think?

**Comment by Emily-Jiang** [comment]
@JanWesterkamp-iJUG are there anything else we should do for this issue?

**Comment by Emily-Jiang** [comment]
This should be done at the microprofile-parent pom.xml if possible.

**Comment by Emily-Jiang** [comment]
I think I have updated all of the dependencies to the latest version. Please reopen if you think otherwise.
