### ISSUE TITLE
Move docs from sandbox

### ISSUE THREAD

**Issue by brunobat** [eclipse/microprofile-telemetry#6]
**Description**
Move these documents:
https://github.com/eclipse/microprofile-sandbox/tree/master/proposals/microprofile-telemetry
To the spec folder.

- [ ] Application user
- [X] Specification implementer

...I need to be able to:

See the Telemetry documentation created in the sandbox

...which enables me to:

Evolve the spec documentation

**Comment by brunobat** [comment]
Still needed:

- I need to send the preliminary work to the README.
- add licenses to the spec
- fix commit email.

**Comment by Emily-Jiang** [comment]
I think this should be closed as all tasks were done. Please reopen if you think something is still missing.
