### ISSUE TITLE
Plan B for MP Telemetry to MP (dafault/core/platform)

### ISSUE THREAD

**Issue by JanWesterkamp-iJUG** [eclipse/microprofile-telemetry#66]
The current situation:

MP Telemetry has a narrow coupling to OpenTelemetry, which has a Specification, a Java (API) and a Java Instrumentation.
The OpenTelemetry Specification itself has dependencies on i.e. W3C Specifications etc...

Especially the SDK (disablement/enablement) configuration property used for controlling the activity and default behaviour is in the current at the MPWG decided use a blocker for the MP Telemetry release and that results - as MP Telemetry is a required spec in MP itself - to a blocker for the hole MP 6.0 release, as it is on the ciritical path of the project now!

A delay has occoured already and further delay is expected as the last OpenTelemetry Java release does not reference the OpenTelemetry Specification release, that was released 2 days before ([see details here](https://github.com/eclipse/microprofile-telemetry/pull/60#issuecomment-1279330009)).

Here are options for solving this situation:

- Using a MP namespace property for SDK enablement for decoupling (that approach was denied by the MPWG in the past)
- Using the former experimental property in MP Telemetry 1.0 (with different default behaviour and is bad spec design, as this can change at any time, or better in this case has been changed already in spec version 1.14.0)
- Waiting again that the OpenTelemetry Java implementation (> 1.19.0) including instrumentation picks the current spec version 1.14.0 with the final SDK property and us this as dependency in MP Telemetry (still with deviating default behaviour) and further delaying MP 6.0
- Allowing both of the SDK paramters, the final one and the experimental one (while deprecating the last already) for MP Telemetry 1.0 implementations (could at least prevent a breaking change very soon but it will occure immediately, when the OpenTelemetry Java implementation drops the experimental one)
- Using the old OpenTelemetry Specification version 1.13.0 with the Java version 1.19.0 and use the configuration paramter that exisits in the last already and is defined final in spec version 1.14.0 then (still with deviating default behaviour. That's what the MP Telemetry Spec Team decided currently).
- Decouple MP Telemetry from MP (default/core/platform) by release it as an additional, separate spec besides MP (non-requirement)

The last option has multiple advantages:

- MP 6.0 is not blocked anymore (by MP Telemetry)
- MP Telemetry 1.0 can pick up the next OpenTelemetry Java and Java Instrumentation releases, when they are available and use the final SDK configuration property
- Additionally, when not part of the default MP release, the default bahaviour of OpenTelemetry (default enabled) can be addopted in MP Telemetry too (currently default disabled), as this is controlled now by adding MP Telemetry to MP by the user (as in other OpenTelemetry use cases)!

Following this approach would be in sync with MP best practice to have a component spec release before being able to add it to the platform too. There where good reasons like having a drop in replacement for OpenTracing support to deviate from that, but the narrow coupling has severe impact on the MP release now - and in the future.

The drawback of having no drop in replacement for MP OpenTracing could be explaind as an advantage for the user instead: Now the user can decide what to use, there is an additonal offering for a replacement, the option to futher use OpenTracing (by adding this to MP 6.0 manually). And there is even much more, where we have a lack of marketing at the moment:

- MP Context Propagation
- MP GraphQL
- MP LRA
- MP Reactive Messaging
- MP Reactive Stream Operators
- MP Service Mesh (?)

in addition to:

- MP OpenTracing (new here as standalone)
- MP Telemetry (new here as standalone)

Some of this componenten specs need maintenence and may be MP aligned releases - not only for MP 6.0. But an investment in this could turn somthing sad into somthing nice, that could (and should) be communicated to the MP community.

If MPWG agrees on the last, this architectue approach should be part of the MP Program Plan 2023 too of course.

At least, we could even decide to add MP Telemetry to a later - even minor - release of MP (default/core/platform), but then we might have to rethink about the default behaviour of the SDK property.

**Comment by Emily-Jiang** [comment]
We discussed in the call yesterday not to go with this plan B. The group would like to get MP OTel released asap to stay away fro the deprecated technology OpenTracing.

**Comment by Emily-Jiang** [comment]
no longer an issue.
