### ISSUE TITLE
TCK cannot be run using the Arquillian REST protocol

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-telemetry#72]
**Describe the bug**

Arquillian recently introduced the [REST 3.0 testing protocol](https://github.com/arquillian/arquillian-core/issues/408) to allow remote and managed testing in environments where the servlet APIs are not present.

It would be nice to be able to use this so that the MP Telemetry TCK can be run in an environment which strictly only provides Jakarta EE core (which does not include servlet).

However, the rest requests made by arquillian have spans created for them which causes some of our tests to fail because there are more spans than expected collected by the `InMemorySpanExporter`.

We could fix this by either detecting and ignoring spans created by arquillian, or by somehow marking the spans which are part of the test.

**Comment by Emily-Jiang** [comment]
@Azquelt does this need to be fixed prior to 1.0 release?
