### ISSUE TITLE
The spec asciidoc directly displaying the variable  {otel-spec-main-version} without being substituated in the github repo

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-telemetry#87]
In the spec ascii doc, we have the following:
This document and implementations MUST comply with the following OpenTelemetry {otel-spec-main-version} specifications:

{otel-spec-main-version} is only evaluated at the final built version but not at the github repo. We need to find a solution for this.

**Comment by JanWesterkamp-iJUG** [comment]
This is bacause GitHub does not evaluate the POM for the preview shown.

The preview is very limited at the moment. Options from my view are:

- We could file an issue at GitHub to solve it there
- We can add a workaround, showing where to find the variable definition
- Maintain this manually on different locations again (not recommended!)
- Ignore this

As this is a preview, it's ok showing the variable name only on my opinion.

**Comment by Emily-Jiang** [comment]
okay, let's ignore the broken link for now and hope github can provide a solution. @JanWesterkamp-iJUG would you like to file a github issue to solve it in the future?
