### ISSUE TITLE
Missing TCK tests

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-telemetry#89]
The following things are required by the spec but not tested by the TCK:

- [x] All required semantic convention attributes for HTTP 
  - We do test several attributes, I think we're missing `net.host.name` and `http.route` for server spans and `net.peer.name` for client spans
- [x] Using different propagation formats, including that the right headers are set
  - [x] tracecontext
  - [x] baggage
  - [x] b3
  - [x] jaeger
- [x] Each of the available [config options](https://github.com/open-telemetry/opentelemetry-java/tree/v1.19.0/sdk-extensions/autoconfigure)
  - Some won't be possible to test (e.g. most of the exporter options). It would be good to produce a list of what the TCK doesn't cover for implementors
- [x] Use of async programming models for JAX-RS server, JAX-RS client and MP Rest Client
  - OTel's `Context` (which is used to determine the current `Span` and `Baggage`) uses a thread local by default, so it's easy to make mistakes in the implementation which show up as bugs when using async APIs.
- [x] Use of each of the extension points in the [autoconfigure SPI](https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/latest/index.html) which are relevant to tracing
  - See also #91 
- [x] Use of an injected `OpenTelemetry` bean

**Comment by Emily-Jiang** [comment]
@yasmin-aumeeruddy please take a look to see whether you can contribute to the list of missing TCKs.

**Comment by yasmin-aumeeruddy** [comment]
Noting each of the available [config options](https://github.com/eclipse/microprofile-telemetry/blob/main/tracing/spec/src/main/asciidoc/microprofile-telemetry-tracing-spec.asciidoc#configuration) specified in the spec. 
- [ ] otel.sdk.disabled
- [ ] otel.traces.exporter
- [ ] otel.propagators 
- [ ] otel.resource.attributes
- [ ] otel.service.name 
- [ ] otel.bsp.schedule.delay 
- [ ] otel.bsp.max.export.batch.size
- [ ] otel.bsp.export.timeout
- [ ] otel.traces.sampler 
- [ ] otel.exporter.otlp.protocol
- [ ] otel.exporter.otlp.traces.protocol 
- [ ] otel.exporter.otlp.endpoint
- [ ] otel.exporter.otlp.traces.endpoint
- [ ] otel.exporter.otlp.certificate
- [ ] otel.exporter.otlp.traces.certificate
- [ ] otel.exporter.otlp.client.key
- [ ] otel.exporter.otlp.traces.client.key 
- [ ] otel.exporter.otlp.traces.client.certificate 
- [ ] otel.exporter.otlp.headers
- [ ] otel.exporter.otlp.traces.headers 
- [ ] otel.exporter.otlp.compression 
- [ ] otel.exporter.otlp.traces.compression 
- [ ] otel.exporter.otlp.timeout
- [ ] otel.exporter.otlp.traces.timeout

**Comment by brunobat** [comment]
I think we should only support the exporter related properties if:
* Implementations must provide their own exporter, not based on OKHttp
* Tests for those properties might need a reference application capable to run on all MP implementations. 
* Exporter based tests might need IT tests with a collector.

**Comment by Azquelt** [comment]
I agree that most of the exporter properties are hard to test and would require some kind of integration test using a collector.

The `otel.bsp.export` properties govern how spans are batched together before being exported. I think this takes effect on a custom exporter, so we should be able to test those, but the tests would be somewhat slow and prone to timing issues.

I did wonder if we can just check that the properties make it into the config object if it's set. I'm not sure if that's possible, I think the autoconfigure SPI would let us see the whole config, but I'm not sure we could guarantee that the implementation doesn't do something with the config after we see it.
