### ISSUE TITLE
Clarify which API classes must be available to users

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-telemetry#91]
**Description**

The spec is not explicit about which classes and packages should be available to applications.

The closest I can find is this:

> This document and implementations MUST comply with the following OpenTelemetry 1.13 specifications:
> - [OpenTelemetry Overview](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.13.0/specification/overview.md)
> - [Tracing API](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.13.0/specification/trace/api.md)
> - [Baggage API](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.13.0/specification/baggage/api.md)
> - [Context API](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.13.0/specification/context)
> - [Resource SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.13.0/specification/resource/sdk.md)

The spec has several examples of using API classes, and the TCK also assumes that the autoconfigure SPI is available as the `InMemorySpanExporterProvider` implements one of its interfaces.

The spec should be more explicit about which API classes are required and we should have TCK tests to assert that they are available.

**Comment by Emily-Jiang** [comment]
This involves spec clarification and TCK verification (load the classes and/or use the classes).

**Comment by Emily-Jiang** [comment]
In the next call, we will work out the list of API classes to be exposed under this spec.

**Comment by Azquelt** [comment]
Here are the API packages I think are required.

### Tracing API

- [io.opentelemetry.api](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/1.27.0/io/opentelemetry/api/package-summary.html)
- [io.opentelemetry.api.trace](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/1.27.0/io/opentelemetry/api/trace/package-summary.html)
- [io.opentelemetry.api.common](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/1.27.0/io/opentelemetry/api/common/package-summary.html)

Note: `io.opentelemetry.api` does depend on [io.opentelemetry.api.metrics](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/1.27.0/io/opentelemetry/api/metrics/package-summary.html) and [io.opentelemetry.api.logs](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/1.27.0/io/opentelemetry/api/logs/package-summary.html), though we only support the parts of it that relate to tracing.

### Baggage API

- [io.opentelemetry.api.baggage](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/1.27.0/io/opentelemetry/api/baggage/package-summary.html)
- [io.opentelemetry.api.baggage.propagation](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/1.27.0/io/opentelemetry/api/baggage/propagation/package-summary.html)

### Context API

- [io.opentelemetry.context](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-context/1.27.0/io/opentelemetry/context/package-summary.html)
- [io.opentelemetry.context.propagation](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-context/1.27.0/io/opentelemetry/context/propagation/package-summary.html)

### Resource SDK

- [io.opentelemetry.sdk.resources](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-common/1.27.0/io/opentelemetry/sdk/resources/package-summary.html)

### Autoconfigure SPI

This is the programmatic interface that allows users to register extensions when using the SDK Autoconfigure Extension (which we use for configuration). The spec currently isn't clear about whether or not support for the SPI is required, but the TCK currently requires it to register a `SpanExporter`.

- [io.opentelemetry.sdk.autoconfigure.spi](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/1.27.0/io/opentelemetry/sdk/autoconfigure/spi/package-summary.html)
- [io.opentelemetry.sdk.autoconfigure.spi.traces](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/1.27.0/io/opentelemetry/sdk/autoconfigure/spi/traces/package-summary.html)
- these then depend on the following packages
  - [io.opentelemetry.sdk.trace](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-trace/1.27.0/io/opentelemetry/sdk/trace/package-summary.html)
  - [io.opentelemetry.sdk.trace.data](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-trace/1.27.0/io/opentelemetry/sdk/trace/data/package-summary.html)
  - [io.opentelemetry.sdk.trace.export](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-trace/1.27.0/io/opentelemetry/sdk/trace/export/package-summary.html)
  - [io.opentelemetry.sdk.trace.samplers](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-trace/1.27.0/io/opentelemetry/sdk/trace/samplers/package-summary.html)
  - [io.opentelemetry.sdk.common](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-common/1.27.0/io/opentelemetry/sdk/common/package-summary.html)

### `WithSpan` annotation

I see this now also contains an `AddingSpanAttributes` annotation which sets attributes on the current span without creating a new one. We should decide whether to support that.

- [io.opentelemetry.instrumentation.annotations](https://www.javadoc.io/doc/io.opentelemetry.instrumentation/opentelemetry-instrumentation-annotations/latest/io/opentelemetry/instrumentation/annotations/package-summary.html)

### Semantic Conventions

We say that the implementation needs to follow semantic conventions. It makes sense to also expose the semantic convention APIs to the user. The TCK currently requires that these APIs are available, though we could change the TCK to package the classes in the test application.

Note that these packages are not stable.

- [io.opentelemetry.semconv.trace.attributes](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-semconv/1.27.0-alpha/io/opentelemetry/semconv/trace/attributes/package-summary.html)
- [io.opentelemetry.semconv.resource.attributes](https://www.javadoc.io/static/io.opentelemetry/opentelemetry-semconv/1.27.0-alpha/io/opentelemetry/semconv/resource/attributes/package-summary.html)

**Comment by Emily-Jiang** [comment]
@Azquelt since we are not sure which spec version we should link to, it might be problematic to link to the spec with a particular release version. We can discuss how best to provide the info on the call.

**Comment by Azquelt** [comment]
All of the links that I've provided above link to opentelemetry-java javadoc (or opentelemetry-java-instrumentation for the annotations), not to the opentelemetry spec.

I assume we're going to specify either a minimum version of opentelemetry-java, or a version of opentelemetry-java which implementations must be compatible with, in which case we can link to that version.

**Comment by brunobat** [comment]
I wonder if we could divide the tests and, therefore, the required packages in 2 types:
* end users.
* integrators.
